name: Auto Run and Push

on:
  schedule:
    - cron: '0 4,12,16 * * *'
    - cron: '30 6 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run script
        run: python main.py --data_dir data

      - name: Commit and push changes
        env:
          ACTIONS_PAT: ${{ secrets.ACTIONS_PAT }}
        run: |
          git config --global user.name 'P0W'
          git config --global user.email 'powprashant@gmail.com'
          git add .
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit"
          else
            if git diff --cached --name-only | grep -q '_list.csv'; then
              COMMIT_MESSAGE="Indices changed - $(date)"
            else
              COMMIT_MESSAGE="Add new CSV and JSON files - $(date)"
            fi
            git commit -m "$COMMIT_MESSAGE"
            git pull --rebase https://P0W:${{ secrets.ACTIONS_PAT }}@github.com/P0W/nse_indices.git main
            git push https://P0W:${{ secrets.ACTIONS_PAT }}@github.com/P0W/nse_indices.git HEAD:main
            echo "Code successfully committed and pushed with message: $COMMIT_MESSAGE"
          fi

